// Machine-readable self-description so an agent can introspect adaptogen's full
// surface without reading source: the verbs it can call, the typed error codes a
// Result may carry, the guard DSL grammar, and the enforcement levels. Pure data
// plus describe(); ASCII only.

import { ERROR_CODES } from "./errors.js";
import { DEFAULT_TUNABLES } from "./config.js";

export const MANIFEST = {
  name: "adaptogen",
  summary:
    "Agent-owned, self-evolving DAG+FSM state store: durable memory, policy, and intuition in one event-sourced graph.",
  enforcement: {
    levels: ["off", "soft", "hard"],
    meaning: {
      off: "transition always allowed (an explicit gate through a boundary)",
      soft: "transition warned and recorded as a soft violation, still applied; auto-promotes to hard after escalationThreshold soft violations on the edge",
      hard: "transition denied (BlockedAttempt recorded, cursor does not move); auto-demotes back to soft after demotionCleanRuns consecutive clean uses",
    },
    precedence: "edge enforcement overrides zone, which overrides defaultEnforcement; strictest deciding reason wins",
  },
  errorCodes: ERROR_CODES,
  errorHints: {
    NotFound: "the id does not exist; create it (remember/link) or query getNode/recall first",
    DuplicateId: "an id collision; choose a fresh id or upsert the existing one",
    InvalidInput: "malformed argument (bad id charset, non-finite weight, empty cursor); fix the value",
    PayloadTooLarge: "payload exceeds maxPayloadBytes; shrink it or raise the tunable",
    CycleRejected: "a dependency edge would close a loop; reorder or drop an edge (details.cycle has the path)",
    IllegalTransition: "no enabled edge from the cursor to the target; check legalMoves()/suggest()",
    HardBlocked: "a hard enforcement reason denied the move; setEnforcement(edge,'off') to gate, or pick another move",
    GuardParseError: "the guard DSL string did not compile; see the message for the offending token",
    IntegrityBroken: "hash-chain break; run verifyIntegrity()/repair(), restore from a checkpoint",
    LockHeld: "another writer holds the db lock; close it or open with lock:false (single-writer only)",
    Conflict: "optimistic-concurrency or branch mismatch; re-read and retry",
    ZoneNotFound: "no such zone; defineZone() first or check zones()",
    CheckpointNotFound: "no checkpoint by that name; listCheckpoints()",
    MigrationError: "the migrate() apply fn threw or returned an invalid node; see the message",
    InvalidConfig: "tunable out of range; see tunables.ranges",
    NoMoves: "no legal move from the cursor; link() a move, relax enforcement, or setCursor() elsewhere",
  },
  guardDSL: {
    summary:
      "loop-free, depth- and length-bounded predicate over a read-only context; no eval/Function; own-property paths only (rejects __proto__/prototype/constructor)",
    operators: ["&&", "||", "!", "==", "!=", ">", ">=", "<", "<=", "in", "has"],
    literals: ["number", "'string'", "true", "false", "null", "[a, b, ...]"],
    context: [
      "from", "to", "fromTags", "toTags", "fromKind", "toKind",
      "edge.label", "edge.weight",
      "stat.visits", "stat.emaReward", "stat.successes", "stat.failures",
      "vars.*",
    ],
    missingKey: "an unknown path reads as undefined; comparisons against it are false (a guard never throws on a missing key)",
    operatorNotes: "'in': membership in a literal array (x in [a,b]); 'has': array/string contains (fromTags has 'urgent')",
    examples: [
      "stat.failures < 3",
      "stat.visits >= 5 && vars.approved == true",
      "fromKind == 'state' && toKind == 'state'",
      "toTags has 'safe' || edge.weight >= 2",
      "!(vars.dryRun == true)",
    ],
  },
  verbs: {
    compose: [
      ["plan", "({ nodes:[id|{id,kind?,label?,payload?,tags?,status?}], transitions:[[from,to,opts?]|{from,to,...opts}], deps:[[node,prereq]|{node,prereq}], cursor?:[id] }) -> Result<{nodes,transitions,deps,cursor}> -- atomic, all-or-nothing bulk graph builder; validates the whole spec (ids, endpoints, guards, weights, batch acyclicity, cursor) before writing anything, so a failure leaves zero events. An endpoint resolves if pre-existing OR declared in spec.nodes."],
      ["orient", "(vars?) -> { cursor, suggestions, legalMoves, blocked[{to,reasons}], ready, violations, integrity_ok, recent, seq, ftsEnabled, tunables, done } -- one situational snapshot a cold/returning agent reads to decide its next move; pure read."],
    ],
    memory: [
      ["remember", "{ id, kind?, label?, payload?, tags?, status?, embedding?, expectVersion? } -> Result<DNode>"],
      ["getNode", "(id) -> DNode | null"],
      ["recall", "({ id?, kind?, tag?, status?, text?, embedding?, limit? }) -> DNode[]"],
      ["setStatus", "(id, status) -> Result<DNode>"],
      ["archive", "(id) -> Result<DNode>"],
      ["deprecate", "(id) -> Result<DNode>"],
    ],
    edges: [
      ["link", "(from, to, { id?, kind?, label?, guard?, enforcement?, weight? }) -> Result<DEdge>; weight must be a finite number >= 0"],
      ["depend", "(node, prereq, opts?) -> Result<DEdge>"],
      ["unlink", "(edgeId) -> Result<true>"],
      ["setEnforcement", "(edgeId, mode) -> Result<DEdge>"],
    ],
    fsm: [
      ["cursor", "() -> NodeId[]"],
      ["setCursor", "(nodes) -> Result<NodeId[]>"],
      ["legalMoves", "(vars?) -> MoveInfo[]"],
      ["explainTransition", "(to, vars?) -> Result<DecisionTrace>"],
      ["transition", "(to, vars?) -> Result<TransitionOutcome>"],
      ["suggest", "(vars?) -> Suggestion[] (each: edgeId,to,score,confidence,enforcement,visits,emaReward,breakdown{reward,weight,explore})"],
      ["step", "({ to?, vars?, reward? }) -> Result<{ to, suggestion, applied, denied, soft_warned, outcome, reward, done }> -- one-call suggest->transition->reward loop"],
      ["reward", "(value, { edgeId?, trace?, depth?, lambda? }) -> Result"],
      ["getStat", "('node'|'edge', id) -> Stat | null (visits, emaReward, successes, failures, blocks, softViolations)"],
    ],
    dag: [
      ["ready", "(done?) -> NodeId[]"],
      ["topo", "() -> { order, cyclic }"],
      ["reachable", "(from, kind?) -> NodeId[]"],
      ["ancestors", "(of, kind?) -> NodeId[]"],
      ["descendants", "(of, kind?) -> NodeId[]"],
    ],
    zones: [
      ["defineZone", "(name, members, { intra?, boundary? }) -> Result<Zone>"],
      ["addToZone", "(name, node) -> Result<Zone>"],
      ["removeFromZone", "(name, node) -> Result<Zone>"],
      ["zonesOf", "(node) -> ZoneName[] (the zones a node belongs to)"],
      ["deriveZone", "(seed, predicate?) -> Result<{ members }>"],
      ["zones", "() -> Zone[]"],
    ],
    evolve: [
      ["splitState", "(nodeId, newId, moveEdgeIds) -> Result"],
      ["mergeStates", "(a, b) -> Result"],
      ["gc", "() -> { deprecated, prunedEdges }"],
      ["migrate", "(kind, apply, toVersion?) -> Result"],
      ["optimize", "() -> OptimizeSuggestion[]"],
      ["reweight", "() -> { reweighted }"],
      ["selfIterate", "() -> Result"],
    ],
    integrity: [
      ["validate", "() -> ValidationReport"],
      ["repair", "() -> { fixed, quarantined }"],
      ["verifyIntegrity", "() -> IntegrityReport"],
    ],
    durability: [
      ["checkpoint", "(name) -> Result<{ seq }>"],
      ["rollback", "(name) -> Result<{ seq }>"],
      ["listCheckpoints", "() -> { name, seq }[]"],
      ["branch", "(filename) -> Result<DState>"],
      ["merge", "(branchDs) -> Result<{ merged }>"],
      ["discard", "() -> void"],
      ["snapshot", "() -> string"],
      ["compact", "(retain?) -> { snapshotId, pruned }"],
      ["export", "() -> ExportBundle"],
    ],
    config: [
      ["getTunables", "() -> Tunables"],
      ["setTunable", "(key, value) -> Result<Tunables>"],
    ],
    observe: [
      ["render", "() -> string (ASCII live view)"],
      ["metrics", "() -> Metrics"],
      ["toMermaid", "() -> string"],
      ["toDot", "() -> string"],
      ["history", "(filter?) -> HistoryEntry[]"],
      ["ftsEnabled", "() -> boolean (false = text recall on the LIKE fallback, not FTS5)"],
      ["describe", "() -> this manifest"],
    ],
  },
  zones: {
    summary: "named safe-transition regions the agent may move within freely while crossing the boundary stays governed",
    meaning: {
      intra: "enforcement applied to moves that stay inside the zone",
      boundary: "enforcement applied to moves that cross the zone edge",
      defineZone: "declare a zone over explicit members",
      deriveZone: "auto-derive members from the reachable subset satisfying a guard predicate, then ratify them as a zone",
    },
  },
  tunables: {
    summary: "agent-settable knobs (setTunable/getTunables); each is range-checked, an out-of-range value is an InvalidConfig Result",
    defaults: DEFAULT_TUNABLES,
    ranges: {
      defaultEnforcement: "off|soft|hard",
      explore: "ucb|epsilon|greedy",
      epsilon: "[0,1]",
      rewardAlpha: "[0,1]",
      ucbC: "[0,100]",
      escalationThreshold: "integer >= 0",
      demotionCleanRuns: "integer >= 0",
      snapshotInterval: "integer >= 0",
      retain: "integer >= 0",
      decayHalfLife: "number >= 1",
      maxPayloadBytes: "integer >= 64",
    },
    meaning: {
      defaultEnforcement: "policy applied when neither edge nor zone overrides it",
      explore: "suggest() strategy: ucb (uncertainty bonus), epsilon (random with prob epsilon), greedy (pure exploit)",
      epsilon: "exploration probability when explore=epsilon",
      rewardAlpha: "EMA learning rate for reward; higher reacts faster, forgets sooner",
      ucbC: "exploration weight under ucb; higher surfaces rarely-tried edges more",
      escalationThreshold: "soft violations on an edge before it auto-promotes to hard (0 disables)",
      demotionCleanRuns: "consecutive clean uses before a hard edge auto-demotes to soft (0 disables)",
      snapshotInterval: "events between automatic snapshots; bounds recovery replay cost",
      retain: "events retained behind the snapshot on compact()",
      decayHalfLife: "seqs over which a stat's reward influence halves, so stale paths lose pull",
      maxPayloadBytes: "cap on a node payload's JSON size",
    },
  },
  patterns: {
    summary: "worked, runnable agent flows (ASCII only); copy and adapt",
    build_a_workflow: [
      "// One atomic call turns a mental plan into a graph; on any error nothing is written.",
      "const r = ds.plan({",
      "  nodes: ['research', { id: 'draft', payload: { words: 0 } }, 'review', 'ship'],",
      "  transitions: [['research', 'draft'], ['draft', 'review'], ['review', 'ship', { guard: \"vars.approved == true\" }]],",
      "  deps: [['draft', 'research'], ['review', 'draft'], ['ship', 'review']],",
      "  cursor: ['research'],",
      "});",
      "if (!r.ok) console.log(r.error.code, r.error.message); // names the offending item by index",
    ],
    orient_then_act: [
      "// A cold or returning agent reads one snapshot, then steps.",
      "const o = ds.orient();",
      "// o: { cursor, suggestions, legalMoves, blocked, ready, violations, integrity_ok, recent, done }",
      "if (!o.done && o.integrity_ok) ds.step({ reward: 1 });",
    ],
    minimal_session: [
      "const ds = Adaptogen.open('./agent.db');",
      "ds.remember({ id: 'plan', payload: { goal: 'ship' } });",
      "ds.remember({ id: 'exec' });",
      "ds.link('plan', 'exec');",
      "ds.setCursor(['plan']);",
      "const r = ds.transition('exec');",
      "if (r.ok && r.value.applied) ds.reward(1);",
      "ds.close();",
    ],
    step_loop: [
      "// Advance the cursor by the learned best move until none remain.",
      "ds.setCursor(['plan']);",
      "let s = ds.step({ reward: 1 });",
      "while (s.ok && !s.value.done) s = ds.step({ reward: 1 });",
      "// s.value: { to, suggestion{breakdown}, applied, soft_warned, done }",
    ],
    checkpoint_rollback: [
      "ds.checkpoint('before-risky');",
      "const r = ds.transition('risky');",
      "if (!ds.validate().ok) ds.rollback('before-risky');",
    ],
    reward_decay: [
      "// Credit the last 3 transitions with exponential decay (lambda).",
      "ds.reward(1, { trace: true, depth: 3, lambda: 0.6 });",
    ],
    zones: [
      "ds.defineZone('safe', ['a', 'b'], { intra: 'off', boundary: 'hard' });",
      "// or auto-derive from a reachable predicate, then ratify:",
      "ds.deriveZone('a', \"toTags has 'safe'\");",
    ],
    self_evolution: [
      "// One safe pass: reweight -> apply safe suggestions -> validate -> rollback on regression.",
      "const r = ds.selfIterate();",
      "// inspect ds.optimize() for candidate edits without applying them",
    ],
  },
};
